security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    # providers:
    #     users_in_memory: { memory: null }
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
        # logout:
        #     path: app_logout
        # main:
        #     anonymous: lazy
        #     provider: users_in_memory

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true
    role_hierarchy:
        ROLE_ADMIN: ADMIN
        ROLE_PAGE_1: [PAGE_1, ADMIN]
        ROLE_PAGE_2: [PAGE_2, ADMIN]
    #Se utilizará el primer control de acceso que coincida
    access_control:
        # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/index, roles: ROLE_ADMIN }
        - { path: ^/page_1, roles: ROLE_PAGE_1 }
        - { path: ^/page_2, roles: ROLE_PAGE_2 }

